const express=require("express")
const app=express()
const bodyparser=require("body-parser")
app.use(bodyparser.json())
const signup=require("./routes/SignUp")
const signin=require("./routes/SignIn")
const deleteAccount=require("./routes/deleteUser")
app.use("/",signup)
app.use("/",signin)
app.use("/",deleteAccount)
app.listen(3001,()=>console.log("server started"))